### PR TITLE
Don't set value if Element has property "value"

### LINKED ISSUE #393: GeneratedVaadinComboBox CTOR is unaware of possibly already existing "value" property in underlying Element
This is failing test:

```
private class ComboBoxWithInitialValue
            extends GeneratedVaadinComboBox<ComboBoxWithInitialValue, String> {
        ComboBoxWithInitialValue() {
            super("", null, String.class, value -> value, value -> value);
        }
    }

@Test
    public void elementHasValue_wrapIntoField_propertyIsNotSetToInitialValue() {
        Element element = new Element("vaadin-combo-box");
        element.setProperty("value", "foo");
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(
                instantiator.createComponent(ComboBoxWithInitialValue.class))
                .thenAnswer(invocation -> new ComboBoxWithInitialValue());
        ComboBoxWithInitialValue field = Component.from(element,
                ComboBoxWithInitialValue.class);
        Assert.assertEquals("foo", field.getElement().getPropertyRaw("value"));
    }
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #393

### CODE REVIEW

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java [hunk 1]
```diff
@@ -1466,21 +1464,54 @@ public GeneratedVaadinComboBox(T initialValue, T defaultValue,
...
+     *            returns a property value
+     * @param <P>
+     *            the property type
+     */
+    public <P> GeneratedVaadinComboBox(T initialValue, T defaultValue,
+            Class<P> elementPropertyType,
+            SerializableBiFunction<R, P, T> presentationToModel,
+            SerializableBiFunction<R, T, P> modelToPresentation) {
+        this(initialValue, defaultValue, elementPropertyType,
+                presentationToModel, modelToPresentation, false);
```
Comment (mshabarov) [inline vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1512]: Why do we use `false` (mandatory value) here? Isn't it better to allow `value` property by default for `GeneratedVaadinComboBox` child classes?

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java [hunk 2]
```diff
@@ -1445,7 +1444,6 @@ public GeneratedVaadinComboBox(T initialValue, T defaultValue,
             boolean acceptNullValues) {
         super("value", defaultValue, acceptNullValues);
         if (initialValue != null) {
-            setModelValue(initialValue, false);
```
Comment (mshabarov) [inline vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1448]: Why don't we need `setModelValue ` anymore? How otherwise the model value will be set?

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java [hunk 3]
```diff
@@ -393,7 +393,7 @@ protected void setPageSize(double pageSize) {
      * the returned value may not be the same as in client side.
      * </p>
      * 
-     * @return the {@code size} property from the webcomponent
+     * @return the {@code size} property fromw the webcomponent
```
Comment (mshabarov) [inline vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:396]:
```suggestion
     * @return the {@code size} property from the webcomponent
```

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java (hunk 2 above)
Comment (mshabarov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1448]: Is it initialised automatically in other place based on `value` property of the web component?

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java (hunk 1 above)
Comment (mshabarov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1512]: I assume `false` is used when the initial value is present as a constructor argument, right?

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java (hunk 2 above)
Comment (denis-anisimov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1448]: The opposite question: why it should be used ?
And this is in fact a good question: why use extra method if everything works without it ?

There is no any failure in any IT/unit tests.
Which proves perfectly that this is extra method.

`setPresentationValue` updates both values: model is updated as a consequence of presentation value change.

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java (hunk 1 above)
Comment (denis-anisimov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1512]: This CTOR is preserved because of backward compatibility.
It has `initialValue`. If I pass an initial value then I expect that it will be set.
The CTOR which allows to use initial value optionally has a flag which has to be specified explicitly: the user should make the exact decision whether the initial value is optional or not.
By default initial value has to be set.

Comment (mshabarov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1512]: Yes, thanks, now it's clear

File: vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java (hunk 2 above)
Comment (mshabarov) [reply vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java:1448]: Yes, you're right, it updated in model as follows:
```
 setter.setElementValue(element, propertyName, presentationValue);
```
in `AbstractSinglePropertyField`. Then it's excessive.

**Review by mshabarov — APPROVED** [review]
